name: scheduled test

on:
    schedule:
        - cron: "27 0 * * 6" # 土曜日 09:27 JST
    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - uses: nines75/composite-action/setup-pnpm@main

            - name: ブラウザをインストール
              run: pnpm pw:install

            - name: テスト実行
              run: pnpm pw
